services:
  - type: web_service
    name: covid-vaccine-tracker-api
    env: docker
    plan: free
    region: oregon
    branch: main
    rootDir: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: API_KEY
        sync: false
